### ISSUE TITLE
Unexpected number

### ISSUE THREAD

**Issue by JulianKingman** [trentm/json#122]
I'm trying to use `json` to add a version number to a second json file in the npm `version` hook. It looks like this:
```bash
json -I -f ./app.json -e 'this.expo.version='"$npm_package_version"
```
Unfortunately, I get this error:
```bash
> app-mobile@1.6.32 version /app-mobile
> json -I -f ./app.json -e 'this.expo.version='"$npm_package_version"

undefined:2
this.expo.version=1.6.32
                     ^^^
SyntaxError: Unexpected number
    at new Function (<anonymous>)
    at main (/usr/local/lib/node_modules/json/lib/json.js:1289:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/json/lib/json.js:1683:5)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
```

I get why it thinks it's a number, but how do I make it see it as a string? Ever combination of quotes that I try either gives me the raw version number (which it thinks is a number), or the string `$npm_package_version`. I read through the docs several times, but couldn't figure it out. Pointers?

**Comment by JulianKingman** [comment]
Hah, just kidding. 14th time is the charm, this was the magic that worked:
```json
"version": "json -I -f ./app.json -e 'this.expo.version=\"'$npm_package_version'\"'",
```
