### ISSUE TITLE
colon and semicolon are not allowed as keys

### ISSUE THREAD

**Issue by smalot** [trentm/json#136]
I encountered this issue when trying to edit in place this file:

```json
{
    "name":"cypress-ci",
    "description":"cypress tests",
    "version":"1.0.0",
    "license": "UNLICENSED",
    "private": true,
    "scripts": {}
}
```
Command lines which generate the issue:
```bash
json -I -f package.json -e 'this.scripts.cypress-cucumber-preprocessor={}'
```
```bash
json -I -f package.json -e 'this.scripts."report:merge"="npx mochawesome-merge --reportDir reports > reports/merged-mochawesome.json"'
```

The error is:

```bash
undefined:3
this.scripts."cypress-cucumber-preprocessor"={}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at new Function (<anonymous>)
    at main (/usr/lib/node_modules/json/lib/json.js:1289:27)
    at Object.<anonymous> (/usr/lib/node_modules/json/lib/json.js:1683:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by NPrada** [comment]
I am having the same issue, I believe it has to do with having a '-' in one of the json keys,
if you try run your command without the '-' it will work without errors, eg:
`json -I -f package.json -e 'this.scripts.cypresscucumberpreprocessor={}'`

**Comment by trentm** [comment]
The argument to `-e` or `-c` is JS code. What you passed there is not legal JavaScript code, so this is by design.

You can do somethjing like this:

```
$ echo '{
    "name":"cypress-ci",
    "description":"cypress tests",
    "version":"1.0.0",
    "license": "UNLICENSED",
    "private": true,
    "scripts": {}
}' | json -e 'this.scripts["cypress-cucumber-preprocessor"] = {}'
{
  "name": "cypress-ci",
  "description": "cypress tests",
  "version": "1.0.0",
  "license": "UNLICENSED",
  "private": true,
  "scripts": {
    "cypress-cucumber-preprocessor": {}
  }
}
```
