### ISSUE TITLE
Race condition/timing issue when creating temp file?

### ISSUE THREAD

**Issue by inator** [trentm/json#82]
I notice this on occasion:

    $ json -I -f package.json -e "this.main={build: '2.0.3-140827.2'}"

    fs.js:543
      return binding.rename(pathModule._makeLong(oldPath),
                     ^
    Error: ENOENT, no such file or directory '/home/host/ap/portal/.package.json-json-21038-1417641325994.tmp'
        at Object.fs.renameSync (fs.js:543:18)
        at printDatasets (/usr/lib/node_modules/jsontool/lib/jsontool.js:1061:12)
        at parseChunk (/usr/lib/node_modules/jsontool/lib/jsontool.js:1597:9)
        at /usr/lib/node_modules/jsontool/lib/jsontool.js:1294:13
        at getInput (/usr/lib/node_modules/jsontool/lib/jsontool.js:704:17)
        at main (/usr/lib/node_modules/jsontool/lib/jsontool.js:1264:9)
        at Object.<anonymous> (/usr/lib/node_modules/jsontool/lib/jsontool.js:1615:5)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)

if I try again it succeeds (sometimes takes several tries):

    $ json -I -f package.json -e "this.main={build: '2.0.3-140827.2'}"
    json: updated "package.json" in-place

I was running 7.0.2, but upgraded to 9.0.2 when I realized that I accidentially installed the the depreciated "jsontool" module rather than "json."  I haven't been able to test enough to see if it pops up again with 9.0.2, but thought I'd open an issue just in case this is an unknown bug in the most current release as well.  Is this a known issue that has already been fixed?

**Comment by corvinb** [comment]
Hi,
It seems to me that this issue is not fixed.  I get the following error on my Windows 7 with node 5.4.1 and json 9.0.3, using in-place editing:

fs.js:729
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: ENOENT: no such file or directory, rename 'C:\src\Branding\s3temp\brands\PXP2oqDhkTPVTWhGxMZBr09XJhB1OuUo\data\.configs.json-json-19108-1453848372028.tmp' -> 'C:\src\Branding\s3temp\brands\PXP2oqDhkTPVTWhGxMZBr09XJhB1OuUo\data\configs.json'
    at Error (native)
    at Object.fs.renameSync (fs.js:729:18)
    at printDatasets (c:\Users\cbazgan\AppData\Roaming\npm\node_modules\json\lib\json.js:1081:12)
    at parseChunk (c:\Users\cbazgan\AppData\Roaming\npm\node_modules\json\lib\json.js:1656:9)
    at c:\Users\cbazgan\AppData\Roaming\npm\node_modules\json\lib\json.js:1336:13
    at getInput (c:\Users\cbazgan\AppData\Roaming\npm\node_modules\json\lib\json.js:724:17)
    at main (c:\Users\cbazgan\AppData\Roaming\npm\node_modules\json\lib\json.js:1306:9)
    at Object.<anonymous> (c:\Users\cbazgan\AppData\Roaming\npm\node_modules\json\lib\json.js:1674:5)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)

I've tried with various versions of node with the same result.  I am not familiar with debugging node modules to be able to fix this issue, but looking at the json.js:1082/3 lines, what guarantee is there that the stream/file is closed before the call to fs.renameSync?  It seems like the end() function is asynchronous and that there's a race condition.  The end() function even has a callback for when the stream is closed.
